repos:
  - repo: local
    hooks:
      - id: ensure-no-gcloud-directory
        name: Ensure there's no gcloud directory in the commit
        entry: ./.hooks/pre-commit.sh
        language: script
        always_run: true
        files: .*
        stages: [pre-commit]

      - id: run-approval-tests
        name: Run Hestia CI approval tests
        entry: ./.hooks/approval-tests.sh
        language: script
        files: .*
        stages: [pre-push]
